'=============================================================================
' ram.h - GCBASIC library
'
' ClearRAM - zero every byte of usable General Purpose RAM on the chip,
' including shared/access-bank RAM recovered from [NoBankRAM] that has no
' overlap with [FreeRAM] (see 01_BuildMemoryMap_patch.bi's shared-RAM pass).
'
' USAGE
'   ClearRAM
'
'   Optional. Only pulled into your compiled program if you actually call it.
'   Call it as the first statement in your Main code:
'
'       Main:
'         ClearRAM
'         ' ... your program ...
'
'   INITSYS always runs automatically before Main, regardless of where you
'   place this call - so ClearRAM is guaranteed to execute after INITSYS.
'
' HOW IT WORKS
'   Written entirely in plain GCBASIC - no Asm, no #asmraw. FSR0L/FSR0H (or,
'   on classic banked families, FSR/INDF/STATUS.IRP) are ordinary hardware
'   registers, assignable and comparable directly, so the compiler generates
'   correct chip-specific code (bank selection, instruction choice, constant
'   folding) on its own - e.g. an all-zero low byte folds straight to CLRF
'   instead of MOVLW 0 / MOVWF, exactly as confirmed by inspecting real
'   compiler output.
'
'   Two codegen paths, chosen per chip via CHIPFREERAMLINEAR:
'
'   - Families 15/16 (enhanced mid-range 16F1xxx, PIC18): the whole GPR
'     space is reachable through one flat address space via FSR0, so each
'     block is a single Do/Loop walking FSR0L/FSR0H up to the block's end,
'     clearing through POSTINC0 (whose auto-increment is a hardware property
'     of that address, triggered by any write - no special instruction
'     needed).
'
'   - All other (classic banked) families: STATUS.IRP selects which pair
'     of 128-byte banks FSR/INDF currently reaches, then a Do/Loop sweeps FSR
'     from the block's start offset to its end offset, clearing through INDF
'     and incrementing FSR each pass.
'
'   Neither path ever uses an ordinary Dim'd variable for loop state - only
'   FSR0/FSR/INDF/POSTINC0/STATUS, all true hardware registers - so ClearRAM
'   cannot corrupt its own working state while clearing the exact RAM pool
'   it's drawn from.
'
'   Supports up to 50 CHIPFREERAMBLOCKn blocks and up to 10
'   CHIPSHAREDRAMBLOCKn blocks per chip (must match CRMaxSupportedBlocks /
'   CRMaxSupportedSharedBlocks in 01_BuildMemoryMap_patch.bi). Block counts
'   and addresses are compile-time constants, so the #IF guards below strip
'   out every unused block and the unused family path per chip - zero runtime
'   cost for chips with fewer blocks.
'=============================================================================

Sub ClearRAM

  #IF CHIPFREERAMLINEAR = -1

    'Main free-RAM blocks (from [FreeRAM])

    #IF CHIPFREERAMBLOCKS >= 1
      FSR0L = CHIPFREERAMBLOCK1LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK1LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK1LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK1LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 2
      FSR0L = CHIPFREERAMBLOCK2LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK2LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK2LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK2LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 3
      FSR0L = CHIPFREERAMBLOCK3LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK3LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK3LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK3LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 4
      FSR0L = CHIPFREERAMBLOCK4LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK4LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK4LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK4LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 5
      FSR0L = CHIPFREERAMBLOCK5LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK5LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK5LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK5LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 6
      FSR0L = CHIPFREERAMBLOCK6LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK6LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK6LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK6LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 7
      FSR0L = CHIPFREERAMBLOCK7LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK7LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK7LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK7LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 8
      FSR0L = CHIPFREERAMBLOCK8LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK8LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK8LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK8LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 9
      FSR0L = CHIPFREERAMBLOCK9LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK9LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK9LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK9LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 10
      FSR0L = CHIPFREERAMBLOCK10LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK10LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK10LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK10LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 11
      FSR0L = CHIPFREERAMBLOCK11LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK11LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK11LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK11LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 12
      FSR0L = CHIPFREERAMBLOCK12LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK12LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK12LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK12LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 13
      FSR0L = CHIPFREERAMBLOCK13LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK13LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK13LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK13LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 14
      FSR0L = CHIPFREERAMBLOCK14LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK14LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK14LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK14LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 15
      FSR0L = CHIPFREERAMBLOCK15LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK15LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK15LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK15LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 16
      FSR0L = CHIPFREERAMBLOCK16LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK16LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK16LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK16LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 17
      FSR0L = CHIPFREERAMBLOCK17LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK17LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK17LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK17LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 18
      FSR0L = CHIPFREERAMBLOCK18LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK18LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK18LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK18LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 19
      FSR0L = CHIPFREERAMBLOCK19LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK19LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK19LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK19LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 20
      FSR0L = CHIPFREERAMBLOCK20LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK20LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK20LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK20LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 21
      FSR0L = CHIPFREERAMBLOCK21LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK21LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK21LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK21LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 22
      FSR0L = CHIPFREERAMBLOCK22LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK22LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK22LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK22LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 23
      FSR0L = CHIPFREERAMBLOCK23LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK23LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK23LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK23LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 24
      FSR0L = CHIPFREERAMBLOCK24LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK24LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK24LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK24LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 25
      FSR0L = CHIPFREERAMBLOCK25LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK25LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK25LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK25LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 26
      FSR0L = CHIPFREERAMBLOCK26LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK26LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK26LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK26LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 27
      FSR0L = CHIPFREERAMBLOCK27LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK27LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK27LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK27LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 28
      FSR0L = CHIPFREERAMBLOCK28LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK28LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK28LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK28LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 29
      FSR0L = CHIPFREERAMBLOCK29LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK29LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK29LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK29LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 30
      FSR0L = CHIPFREERAMBLOCK30LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK30LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK30LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK30LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 31
      FSR0L = CHIPFREERAMBLOCK31LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK31LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK31LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK31LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 32
      FSR0L = CHIPFREERAMBLOCK32LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK32LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK32LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK32LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 33
      FSR0L = CHIPFREERAMBLOCK33LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK33LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK33LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK33LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 34
      FSR0L = CHIPFREERAMBLOCK34LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK34LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK34LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK34LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 35
      FSR0L = CHIPFREERAMBLOCK35LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK35LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK35LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK35LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 36
      FSR0L = CHIPFREERAMBLOCK36LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK36LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK36LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK36LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 37
      FSR0L = CHIPFREERAMBLOCK37LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK37LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK37LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK37LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 38
      FSR0L = CHIPFREERAMBLOCK38LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK38LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK38LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK38LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 39
      FSR0L = CHIPFREERAMBLOCK39LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK39LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK39LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK39LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 40
      FSR0L = CHIPFREERAMBLOCK40LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK40LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK40LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK40LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 41
      FSR0L = CHIPFREERAMBLOCK41LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK41LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK41LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK41LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 42
      FSR0L = CHIPFREERAMBLOCK42LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK42LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK42LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK42LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 43
      FSR0L = CHIPFREERAMBLOCK43LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK43LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK43LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK43LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 44
      FSR0L = CHIPFREERAMBLOCK44LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK44LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK44LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK44LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 45
      FSR0L = CHIPFREERAMBLOCK45LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK45LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK45LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK45LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 46
      FSR0L = CHIPFREERAMBLOCK46LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK46LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK46LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK46LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 47
      FSR0L = CHIPFREERAMBLOCK47LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK47LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK47LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK47LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 48
      FSR0L = CHIPFREERAMBLOCK48LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK48LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK48LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK48LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 49
      FSR0L = CHIPFREERAMBLOCK49LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK49LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK49LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK49LFSREND / 256)
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 50
      FSR0L = CHIPFREERAMBLOCK50LFSR AND 255
      FSR0H = CHIPFREERAMBLOCK50LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPFREERAMBLOCK50LFSREND AND 255) And FSR0H = (CHIPFREERAMBLOCK50LFSREND / 256)
    #ENDIF

    'Shared RAM blocks recovered from [NoBankRAM] (not already in [FreeRAM])

    #IF CHIPSHAREDRAMBLOCKS >= 1
      FSR0L = CHIPSHAREDRAMBLOCK1LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK1LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK1LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK1LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 2
      FSR0L = CHIPSHAREDRAMBLOCK2LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK2LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK2LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK2LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 3
      FSR0L = CHIPSHAREDRAMBLOCK3LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK3LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK3LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK3LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 4
      FSR0L = CHIPSHAREDRAMBLOCK4LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK4LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK4LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK4LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 5
      FSR0L = CHIPSHAREDRAMBLOCK5LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK5LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK5LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK5LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 6
      FSR0L = CHIPSHAREDRAMBLOCK6LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK6LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK6LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK6LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 7
      FSR0L = CHIPSHAREDRAMBLOCK7LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK7LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK7LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK7LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 8
      FSR0L = CHIPSHAREDRAMBLOCK8LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK8LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK8LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK8LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 9
      FSR0L = CHIPSHAREDRAMBLOCK9LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK9LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK9LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK9LFSREND / 256)
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 10
      FSR0L = CHIPSHAREDRAMBLOCK10LFSR AND 255
      FSR0H = CHIPSHAREDRAMBLOCK10LFSR / 256
      Do
        POSTINC0 = 0
      Loop Until FSR0L = (CHIPSHAREDRAMBLOCK10LFSREND AND 255) And FSR0H = (CHIPSHAREDRAMBLOCK10LFSREND / 256)
    #ENDIF

  #ELSE

    'Classic banked families: STATUS.IRP selects the bank pair, FSR sweeps
    'within it.

    'Main free-RAM blocks (from [FreeRAM])

    #IF CHIPFREERAMBLOCKS >= 1
      #IF CHIPFREERAMBLOCK1IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK1FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK1FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 2
      #IF CHIPFREERAMBLOCK2IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK2FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK2FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 3
      #IF CHIPFREERAMBLOCK3IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK3FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK3FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 4
      #IF CHIPFREERAMBLOCK4IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK4FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK4FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 5
      #IF CHIPFREERAMBLOCK5IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK5FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK5FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 6
      #IF CHIPFREERAMBLOCK6IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK6FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK6FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 7
      #IF CHIPFREERAMBLOCK7IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK7FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK7FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 8
      #IF CHIPFREERAMBLOCK8IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK8FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK8FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 9
      #IF CHIPFREERAMBLOCK9IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK9FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK9FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 10
      #IF CHIPFREERAMBLOCK10IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK10FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK10FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 11
      #IF CHIPFREERAMBLOCK11IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK11FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK11FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 12
      #IF CHIPFREERAMBLOCK12IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK12FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK12FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 13
      #IF CHIPFREERAMBLOCK13IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK13FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK13FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 14
      #IF CHIPFREERAMBLOCK14IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK14FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK14FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 15
      #IF CHIPFREERAMBLOCK15IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK15FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK15FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 16
      #IF CHIPFREERAMBLOCK16IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK16FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK16FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 17
      #IF CHIPFREERAMBLOCK17IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK17FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK17FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 18
      #IF CHIPFREERAMBLOCK18IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK18FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK18FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 19
      #IF CHIPFREERAMBLOCK19IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK19FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK19FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 20
      #IF CHIPFREERAMBLOCK20IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK20FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK20FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 21
      #IF CHIPFREERAMBLOCK21IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK21FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK21FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 22
      #IF CHIPFREERAMBLOCK22IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK22FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK22FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 23
      #IF CHIPFREERAMBLOCK23IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK23FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK23FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 24
      #IF CHIPFREERAMBLOCK24IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK24FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK24FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 25
      #IF CHIPFREERAMBLOCK25IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK25FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK25FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 26
      #IF CHIPFREERAMBLOCK26IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK26FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK26FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 27
      #IF CHIPFREERAMBLOCK27IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK27FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK27FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 28
      #IF CHIPFREERAMBLOCK28IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK28FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK28FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 29
      #IF CHIPFREERAMBLOCK29IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK29FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK29FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 30
      #IF CHIPFREERAMBLOCK30IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK30FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK30FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 31
      #IF CHIPFREERAMBLOCK31IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK31FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK31FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 32
      #IF CHIPFREERAMBLOCK32IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK32FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK32FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 33
      #IF CHIPFREERAMBLOCK33IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK33FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK33FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 34
      #IF CHIPFREERAMBLOCK34IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK34FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK34FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 35
      #IF CHIPFREERAMBLOCK35IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK35FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK35FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 36
      #IF CHIPFREERAMBLOCK36IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK36FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK36FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 37
      #IF CHIPFREERAMBLOCK37IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK37FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK37FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 38
      #IF CHIPFREERAMBLOCK38IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK38FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK38FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 39
      #IF CHIPFREERAMBLOCK39IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK39FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK39FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 40
      #IF CHIPFREERAMBLOCK40IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK40FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK40FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 41
      #IF CHIPFREERAMBLOCK41IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK41FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK41FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 42
      #IF CHIPFREERAMBLOCK42IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK42FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK42FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 43
      #IF CHIPFREERAMBLOCK43IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK43FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK43FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 44
      #IF CHIPFREERAMBLOCK44IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK44FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK44FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 45
      #IF CHIPFREERAMBLOCK45IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK45FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK45FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 46
      #IF CHIPFREERAMBLOCK46IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK46FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK46FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 47
      #IF CHIPFREERAMBLOCK47IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK47FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK47FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 48
      #IF CHIPFREERAMBLOCK48IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK48FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK48FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 49
      #IF CHIPFREERAMBLOCK49IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK49FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK49FSR8END
    #ENDIF

    #IF CHIPFREERAMBLOCKS >= 50
      #IF CHIPFREERAMBLOCK50IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPFREERAMBLOCK50FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPFREERAMBLOCK50FSR8END
    #ENDIF

    'Shared RAM blocks recovered from [NoBankRAM] (not already in [FreeRAM])

    #IF CHIPSHAREDRAMBLOCKS >= 1
      #IF CHIPSHAREDRAMBLOCK1IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK1FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK1FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 2
      #IF CHIPSHAREDRAMBLOCK2IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK2FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK2FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 3
      #IF CHIPSHAREDRAMBLOCK3IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK3FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK3FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 4
      #IF CHIPSHAREDRAMBLOCK4IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK4FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK4FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 5
      #IF CHIPSHAREDRAMBLOCK5IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK5FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK5FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 6
      #IF CHIPSHAREDRAMBLOCK6IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK6FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK6FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 7
      #IF CHIPSHAREDRAMBLOCK7IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK7FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK7FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 8
      #IF CHIPSHAREDRAMBLOCK8IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK8FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK8FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 9
      #IF CHIPSHAREDRAMBLOCK9IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK9FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK9FSR8END
    #ENDIF

    #IF CHIPSHAREDRAMBLOCKS >= 10
      #IF CHIPSHAREDRAMBLOCK10IRP = 0
        STATUS.IRP = 0
      #ELSE
        STATUS.IRP = 1
      #ENDIF
      FSR = CHIPSHAREDRAMBLOCK10FSR8
      Do
        INDF = 0
        FSR = FSR + 1
      Loop Until FSR = CHIPSHAREDRAMBLOCK10FSR8END
    #ENDIF

  #ENDIF

End Sub
