// Generated by  : ImageConverter 565 v3.0
// Generated from: rgb.png
// Time generated: 11 Apr 2023, 12:52:23
// Dimensions    : 200 x 116 pixels
// Size          : 46402 bytes
// Sliding Window Compression
//
//
Table rgbcompressed as Word
200, 116
0xF800, 0x1C20
0x968A, 0x2008
0x4C17, 0x1E78
End Table 
//End of table data rgbcompressed
